import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('houston.js','utf8'),shared=fs.readFileSync('loadboard.js','utf8');
function lift(src,name){const m=new RegExp('^([ \\t]*)(?:export )?(?:async )?function '+name+'\\(','m').exec(src);assert.ok(m);return src.slice(m.index,src.indexOf('\n'+m[1]+'}',m.index)+m[1].length+2).replace('export ','');}
function setup(){let redraws=0;const ctx=vm.createContext({houstonState:{sort:{key:'time',dir:'asc'}},state:{activeDate:'2026-10-08',nightShift:false},findDriver:id=>id===1?{name:'Aaron'}:null,renderHoustonBoardTable:()=>redraws++});vm.runInContext(lift(shared,'parseHHMM')+'function houstonNightShiftActive(){return !!state.nightShift;}\n'+lift(source,'sortedHoustonRows')+lift(source,'toggleHoustonSort')+';this.sort=sortedHoustonRows;this.toggle=toggleHoustonSort;',ctx);return {ctx,redraws:()=>redraws};}
const rows=[{id:'late',driverName:'zoe',time:'2030'},{id:'early',driverName:'Bob',time:'09:15'},{id:'blank',driverName:'',time:''},{id:'linked',driverId:1,driverName:'Old name',time:'1010'},{id:'done',driverName:'A',time:'00:01',shiftComplete:true}];
const ids=rows=>Array.from(rows,r=>r.id);
test('time sorts chronologically both ways, with blank times and completed loads last',()=>{const {ctx}=setup();assert.deepEqual(ids(ctx.sort(rows)),['early','linked','late','blank','done']);ctx.toggle('time');assert.deepEqual(ids(ctx.sort(rows)),['late','linked','early','blank','done']);});
test('name sorts by displayed driver profile, alphabetically both ways',()=>{const {ctx}=setup();ctx.toggle('driverName');assert.deepEqual(ids(ctx.sort(rows)),['linked','early','late','blank','done']);ctx.toggle('driverName');assert.deepEqual(ids(ctx.sort(rows)),['late','early','linked','blank','done']);});
test('night-shift times sort by date then clock across midnight',()=>{const {ctx}=setup();ctx.state.nightShift=true;const night=[{id:'morning',shiftDate:'2026-10-09',time:'0200'},{id:'evening',shiftDate:'2026-10-08',time:'2300'}];assert.deepEqual(ids(ctx.sort(night)),['evening','morning']);ctx.toggle('time');assert.deepEqual(ids(ctx.sort(night)),['morning','evening']);});
test('sort preserves source order, row identity and fields; toggles trigger only a redraw',()=>{const {ctx,redraws}=setup();const before=JSON.stringify(rows);const sorted=ctx.sort(rows);assert.equal(JSON.stringify(rows),before);assert.ok(sorted.every(r=>rows.includes(r)));ctx.toggle('driverName');ctx.toggle('driverName');ctx.toggle('time');assert.equal(redraws(),3);assert.equal(ctx.houstonState.sort.dir,'asc');});
test('headers expose sort buttons and delegated click selects requested column',()=>{const {ctx}=setup();let click;ctx.boardTable={addEventListener:(event,fn)=>click=fn};const start=source.indexOf('    boardTable.addEventListener("click", (e) => {');const block=source.slice(start,source.indexOf('\n    });',start)+8);vm.runInContext(block,ctx);click({target:{closest:()=>({dataset:{houstonSort:'driverName'}})}});assert.equal(ctx.houstonState.sort.key,'driverName');assert.equal(ctx.houstonState.sort.dir,'asc');assert.match(source,/data-houston-sort="time" aria-sort=/);assert.match(source,/data-houston-sort="driverName" aria-sort=/);});
