-- Mondelez Load Details support: field-by-field Change History for every load.

create table if not exists public.mondelez_change_history (
  id bigint generated by default as identity primary key,
  mondelez_load_id bigint not null references public.mondelez_loads(id) on delete cascade,
  changed_at timestamptz not null default now(),
  field_name text not null,
  old_value text,
  new_value text,
  changed_by text,
  note text
);

create index if not exists mondelez_change_history_load_idx
  on public.mondelez_change_history(mondelez_load_id, changed_at desc);

alter table public.mondelez_change_history enable row level security;

drop policy if exists internal_select on public.mondelez_change_history;
create policy internal_select on public.mondelez_change_history
  for select to authenticated
  using ((select public.current_app_role()) = any (array['dispatcher','accounting','admin','it']::text[]));

drop policy if exists internal_insert on public.mondelez_change_history;
create policy internal_insert on public.mondelez_change_history
  for insert to authenticated
  with check ((select public.current_app_role()) = any (array['dispatcher','accounting','admin','it']::text[]));

drop policy if exists internal_update on public.mondelez_change_history;
create policy internal_update on public.mondelez_change_history
  for update to authenticated
  using ((select public.current_app_role()) = any (array['dispatcher','accounting','admin','it']::text[]))
  with check ((select public.current_app_role()) = any (array['dispatcher','accounting','admin','it']::text[]));

grant select, insert, update on public.mondelez_change_history to authenticated;

create or replace function public.log_mondelez_load_change()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  actor text := split_part(coalesce((select auth.jwt()->>'email'), (select auth.jwt()->>'sub'), 'unknown user'), '@', 1);
  item record;
begin
  for item in
    select * from (values
      ('location', old.location::text, new.location::text),
      ('shift_date', old.shift_date::text, new.shift_date::text),
      ('aljex_number', old.aljex_number::text, new.aljex_number::text),
      ('delivery_group', old.delivery_group::text, new.delivery_group::text),
      ('start_time', old.start_time::text, new.start_time::text),
      ('driver_app_id', old.driver_app_id::text, new.driver_app_id::text),
      ('trailer_number', old.trailer_number::text, new.trailer_number::text),
      ('return_trailer_number', old.return_trailer_number::text, new.return_trailer_number::text),
      ('stop_count', old.stop_count::text, new.stop_count::text),
      ('notes', old.notes::text, new.notes::text),
      ('driver_name', old.driver_name::text, new.driver_name::text),
      ('miles', old.miles::text, new.miles::text),
      ('carrier_rpm', old.carrier_rpm::text, new.carrier_rpm::text),
      ('carrier_pay_per_stop', old.carrier_pay_per_stop::text, new.carrier_pay_per_stop::text),
      ('carrier_pay', old.carrier_pay::text, new.carrier_pay::text),
      ('fsc', old.fsc::text, new.fsc::text),
      ('additional_charges', old.additional_charges::text, new.additional_charges::text),
      ('revenue_total', old.revenue_total::text, new.revenue_total::text),
      ('revenue_manual', old.revenue_manual::text, new.revenue_manual::text),
      ('route_image_path', old.route_image_path::text, new.route_image_path::text),
      ('tonu', old.tonu::text, new.tonu::text),
      ('highlighted', old.highlighted::text, new.highlighted::text),
      ('shift_complete', old.shift_complete::text, new.shift_complete::text)
    ) as values_to_check(field_name, old_value, new_value)
  loop
    if item.old_value is distinct from item.new_value then
      insert into public.mondelez_change_history
        (mondelez_load_id, field_name, old_value, new_value, changed_by)
      values
        (new.id, item.field_name, item.old_value, item.new_value, actor);
    end if;
  end loop;
  return new;
end;
$$;

drop trigger if exists trg_log_mondelez_load_change on public.mondelez_loads;
create trigger trg_log_mondelez_load_change
after update on public.mondelez_loads
for each row execute function public.log_mondelez_load_change();
