-- Date-scoped rate overrides let dispatch change a location's working rate
-- for one operating day without mutating the permanent base rate card.
create table if not exists public.board_rate_daily_overrides (
  id bigint generated by default as identity primary key,
  location text not null check (location in ('atlanta','delaware','buildingc','houston')),
  rate_date date not null,
  kind text not null check (kind in ('tier','setting')),
  rate_key text not null,
  value numeric(12,4) not null check (value >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  unique (location, rate_date, kind, rate_key)
);

alter table public.board_rate_daily_overrides enable row level security;

revoke all on table public.board_rate_daily_overrides from anon;
grant select, insert, update, delete on table public.board_rate_daily_overrides to authenticated;
grant usage, select on sequence public.board_rate_daily_overrides_id_seq to authenticated;

create policy "internal users can read daily board rates"
on public.board_rate_daily_overrides
for select to authenticated
using (public.current_app_role() in ('dispatcher','accounting','admin','it'));

create policy "internal users can insert daily board rates"
on public.board_rate_daily_overrides
for insert to authenticated
with check (public.current_app_role() in ('dispatcher','accounting','admin','it'));

create policy "internal users can update daily board rates"
on public.board_rate_daily_overrides
for update to authenticated
using (public.current_app_role() in ('dispatcher','accounting','admin','it'))
with check (public.current_app_role() in ('dispatcher','accounting','admin','it'));

create policy "internal users can delete daily board rates"
on public.board_rate_daily_overrides
for delete to authenticated
using (public.current_app_role() in ('dispatcher','accounting','admin','it'));

-- Houston historically stored only the displayed rate, so add an explicit
-- flag to distinguish a dispatcher-entered manual override from an automatic
-- daily/base/driver calculation. Existing Houston rates are treated as
-- automatic so the new hierarchy can take over cleanly.
alter table public.loads_houston
  add column if not exists rate_manual boolean not null default false;
