create extension if not exists pg_net with schema extensions;

create table if not exists public.archive_backup_config (
  id boolean primary key default true check (id),
  enabled boolean not null default false,
  retention_days integer not null default 21 check (retention_days between 1 and 3650),
  destination_provider text not null default 'onedrive',
  destination_label text not null default 'M-J Site Backups',
  destination_share_url text not null,
  cron_secret text not null default encode(extensions.gen_random_bytes(32), 'hex'),
  updated_at timestamptz not null default now()
);

insert into public.archive_backup_config (
  id, enabled, retention_days, destination_provider, destination_label, destination_share_url
)
values (
  true,
  false,
  21,
  'onedrive',
  'M-J Site Backups',
  'https://dandltrans-my.sharepoint.com/:f:/g/personal/opstx_dltransport_com/IgDofiStmkKdRqBKApf8Xm5hAXvRE647xPw05mDmtEuVkLQ?e=EkLdse'
)
on conflict (id) do update set
  retention_days = excluded.retention_days,
  destination_provider = excluded.destination_provider,
  destination_label = excluded.destination_label,
  destination_share_url = excluded.destination_share_url,
  updated_at = now();

create table if not exists public.archive_backup_runs (
  id uuid primary key default extensions.gen_random_uuid(),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running','success','partial','failed','disabled','configuration_required')),
  files_considered integer not null default 0,
  files_archived integer not null default 0,
  files_deleted integer not null default 0,
  bytes_archived bigint not null default 0,
  bytes_downloaded bigint not null default 0,
  error_message text,
  destination_label text,
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.archive_backup_items (
  id bigint generated by default as identity primary key,
  bucket_id text not null,
  object_name text not null,
  source_object_id uuid,
  source_created_at timestamptz,
  source_bytes bigint not null default 0,
  provider text not null default 'onedrive',
  provider_drive_id text,
  provider_item_id text,
  provider_web_url text,
  provider_path text,
  provider_size bigint,
  archived_at timestamptz,
  source_deleted_at timestamptz,
  status text not null default 'pending' check (status in ('pending','archived','failed')),
  last_error text,
  archive_run_id uuid references public.archive_backup_runs(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (bucket_id, object_name)
);

create index if not exists archive_backup_items_status_idx
  on public.archive_backup_items(status, archived_at desc);
create index if not exists archive_backup_runs_started_idx
  on public.archive_backup_runs(started_at desc);

alter table public.archive_backup_config enable row level security;
alter table public.archive_backup_runs enable row level security;
alter table public.archive_backup_items enable row level security;

revoke all on public.archive_backup_config from anon, authenticated;
revoke all on public.archive_backup_runs from anon, authenticated;
revoke all on public.archive_backup_items from anon, authenticated;

create or replace function public.archive_backup_status()
returns jsonb
language sql
security definer
set search_path = public, storage
as $$
  with cfg as (
    select * from public.archive_backup_config where id = true
  ),
  storage_totals as (
    select
      count(*)::bigint as object_count,
      coalesce(sum(coalesce(nullif(o.metadata->>'size','')::bigint, 0)), 0)::bigint as total_bytes
    from storage.objects o
    where o.bucket_id in ('mondelez-routes','trip-sheets')
  ),
  bucket_totals as (
    select coalesce(
      jsonb_object_agg(bucket_id, jsonb_build_object('objects', object_count, 'bytes', total_bytes)),
      '{}'::jsonb
    ) as buckets
    from (
      select
        o.bucket_id,
        count(*)::bigint as object_count,
        coalesce(sum(coalesce(nullif(o.metadata->>'size','')::bigint, 0)), 0)::bigint as total_bytes
      from storage.objects o
      where o.bucket_id in ('mondelez-routes','trip-sheets')
      group by o.bucket_id
    ) s
  ),
  eligible as (
    select
      count(*)::bigint as object_count,
      coalesce(sum(coalesce(nullif(o.metadata->>'size','')::bigint, 0)), 0)::bigint as total_bytes
    from storage.objects o
    left join public.archive_backup_items i
      on i.bucket_id = o.bucket_id
     and i.object_name = o.name
     and i.status = 'archived'
    cross join cfg
    where o.bucket_id in ('mondelez-routes','trip-sheets')
      and o.created_at < now() - make_interval(days => cfg.retention_days)
      and i.id is null
  ),
  last_run as (
    select to_jsonb(r) as row
    from public.archive_backup_runs r
    order by r.started_at desc
    limit 1
  ),
  month_usage as (
    select
      coalesce(sum(bytes_downloaded), 0)::bigint as backup_egress_bytes,
      coalesce(sum(bytes_archived), 0)::bigint as archived_bytes,
      coalesce(sum(files_archived), 0)::bigint as files_archived
    from public.archive_backup_runs
    where started_at >= date_trunc('month', now())
      and status in ('success','partial')
  )
  select jsonb_build_object(
    'retention_days', cfg.retention_days,
    'enabled', cfg.enabled,
    'destination_provider', cfg.destination_provider,
    'destination_label', cfg.destination_label,
    'destination_share_url', cfg.destination_share_url,
    'storage_bytes', storage_totals.total_bytes,
    'storage_objects', storage_totals.object_count,
    'storage_quota_bytes', 1073741824::bigint,
    'buckets', bucket_totals.buckets,
    'eligible_bytes', eligible.total_bytes,
    'eligible_objects', eligible.object_count,
    'last_run', coalesce((select row from last_run), 'null'::jsonb),
    'backup_egress_this_month_bytes', month_usage.backup_egress_bytes,
    'backup_egress_quota_bytes', 5368709120::bigint,
    'archived_this_month_bytes', month_usage.archived_bytes,
    'archived_this_month_files', month_usage.files_archived
  )
  from cfg, storage_totals, bucket_totals, eligible, month_usage;
$$;

grant execute on function public.archive_backup_status() to authenticated;

create or replace function public.archive_backup_candidates(p_limit integer default 250)
returns table (
  object_id uuid,
  bucket_id text,
  object_name text,
  created_at timestamptz,
  bytes bigint,
  mime_type text
)
language sql
security definer
set search_path = public, storage
as $$
  select
    o.id,
    o.bucket_id,
    o.name,
    o.created_at,
    coalesce(nullif(o.metadata->>'size','')::bigint, 0)::bigint,
    coalesce(o.metadata->>'mimetype', 'application/octet-stream')
  from storage.objects o
  join public.archive_backup_config cfg on cfg.id = true
  left join public.archive_backup_items i
    on i.bucket_id = o.bucket_id
   and i.object_name = o.name
   and i.status = 'archived'
  where cfg.enabled = true
    and o.bucket_id in ('mondelez-routes','trip-sheets')
    and o.created_at < now() - make_interval(days => cfg.retention_days)
    and i.id is null
  order by o.created_at asc, o.bucket_id, o.name
  limit greatest(1, least(coalesce(p_limit,250),500));
$$;

revoke all on function public.archive_backup_candidates(integer) from public, anon, authenticated;

create or replace function public.run_image_archive_cron()
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_secret text;
  v_enabled boolean;
begin
  select cron_secret, enabled into v_secret, v_enabled
  from public.archive_backup_config where id = true;

  if coalesce(v_enabled, false) is false then
    return;
  end if;

  perform net.http_post(
    url := 'https://ygsapysqzwrpcimgvaqx.supabase.co/functions/v1/image-archive-onedrive',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-archive-cron', v_secret
    ),
    body := '{"action":"run"}'::jsonb,
    timeout_milliseconds := 120000
  );
end;
$$;

revoke all on function public.run_image_archive_cron() from public, anon, authenticated;

DO $$
DECLARE
  existing_job bigint;
BEGIN
  select jobid into existing_job
  from cron.job
  where jobname = 'mj-image-archive-daily'
  limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
END $$;

select cron.schedule(
  'mj-image-archive-daily',
  '13 08 * * *',
  $$select public.run_image_archive_cron();$$
);
